apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodemanager-deployment
spec:
  selector:
    matchLabels:
      app: nodemanager
  replicas: 1
  template:
    metadata:
      labels:
        app: nodemanager
    spec:
      containers:
        - name: nodemanager
          image: localhost:5000/gradual-nodemanager:8000-stable
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              cpu: 200m
              memory: 200Mi
        - name: nodemanager-heartbeat
          image: localhost:5000/gradual-nodemanager:heartbeat-stable
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: nodemanager
spec:
  type: ClusterIP
  ports:
    - port: 8000
  selector:
    app: nodemanager
